ObTris.Open	   ObTris.StartNew    ObTris.SetUser hk
ObTris.Start	 ObTris.Score
           Actions: left right flipleft flipright drop pause
ObTris.SetKeys  j  k  i  m  h  p  (for right handed)
ObTris.SetKeys  d  f  e  c  g  p  (for left handed)
ObTris.SetKeys  ESC  RETURN  TAB / SPACE p
ObTris.SetKeys  LEFT RIGHT UP DOWN / p
ObTris.SetKeys  LEFT RIGHT UP / DOWN p       <--

System.Date 21 10 23  12 36 00
